### PR TITLE
UI fixes

### LINKED ISSUE #143: Chat Interface -- UI Fixes
- add edly's logo as placeholder
- use colors consistent with edly's branding
- align icons on chat module

Sample Figma File: https://www.figma.com/design/E9CG9MS4UFZoEopSYo6NQl/Untitled?node-id=1-2&t=JzIBwhK8m22SCDv7-1

Figma Make Project: https://www.figma.com/make/MlYmkS0qIGFFD5bGS4LOU8/Web-App-UI-for-Sparkth?p=f&t=o1F5xaeLSwUxa719-0

### PR DESCRIPTION
**Pull request by zaira-bibi**
This PR introduces:

- Unifed the color scheme
  - Edly Green - `primary`
  - Edly Blue - `edly-blue`
  - Edly Gray - `edly-gray`
- Renaming of "Settings" to "My Plugins" 
- Plugins displayed as list items
- Modal for setting plugin configurations
- Revamped login and signup pages
- Fixed Sparkth and user icons / chat icons alignment
- Sparkth logo

Closes #143

### CODE REVIEW

File: frontend/components/AppSidebar.tsx [hunk 1]
```diff
@@ -134,7 +94,7 @@ export default function AppSidebar({
               className="w-8 h-8 rounded-full object-cover"
             />
```
Comment (hamza-56) [inline frontend/components/AppSidebar.tsx]: Missing width and height props.
https://medium.com/@oliviarizona/why-nextjs-require-image-height-and-width-e1784d319fe4
